#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <ArduinoJson.h>
#include "NMEAEngine.h"
HardwareSerial GNSS(1),GPSOut(2);WebServer web(80);WiFiServer tcp(10110);WiFiClient clients[4];NMEAEngine nmea;unsigned long packets=0,invalid=0;
String page(){return R"(<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;font-family:system-ui;background:#08111f;color:#eaf2ff}.top{padding:18px;background:#0d1930;display:flex;justify-content:space-between}.wrap{max-width:1100px;margin:auto;padding:18px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card{background:#12223e;border:1px solid #28456f;border-radius:16px;padding:16px}.label{font-size:11px;color:#9bb0da;text-transform:uppercase}.value{font-size:24px;font-weight:bold;margin-top:6px}.ok{color:#62e6a3}.bad{color:#ff7891}.sats{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.sat{background:#0c1930;padding:12px;border-radius:12px}.bar{height:6px;background:#263e66;border-radius:5px}.fill{height:100%;background:#64b5ff;border-radius:5px}@media(max-width:600px){.wrap{padding:12px}}</style></head><body><div class=top><b>🛰 NavIC GPS Bridge</b><span id=live>● CONNECTING</span></div><main class=wrap><div class=grid><div class=card><div class=label>Position</div><div id=pos class=value>Waiting…</div></div><div class=card><div class=label>Fix</div><div id=fix class=value>—</div></div><div class=card><div class=label>Satellites Used</div><div id=used class=value>—</div></div><div class=card><div class=label>Speed</div><div id=speed class=value>—</div></div><div class=card><div class=label>Altitude</div><div id=alt class=value>—</div></div><div class=card><div class=label>HDOP</div><div id=hdop class=value>—</div></div></div><h3>Satellites in View</h3><div id=sats class=sats></div><h3>Latest NMEA</h3><div class=card><pre id=raw></pre></div></main><script>async function u(){try{let d=await(await fetch('/api/live')).json();live.textContent='● LIVE · '+d.packets;live.className='ok';fix.textContent=d.fix?'VALID FIX':'NO FIX';fix.className=d.fix?'value ok':'value bad';pos.textContent=d.latitude.toFixed(6)+', '+d.longitude.toFixed(6);used.textContent=d.satellites;speed.textContent=d.speed_kmh.toFixed(1)+' km/h';alt.textContent=d.altitude.toFixed(1)+' m';hdop.textContent=d.hdop||'—';raw.textContent=d.last_nmea;sats.innerHTML=d.satellite_view.map(s=>'<div class=sat><b>'+s.constellation+' '+s.prn+'</b><br>'+s.snr+' dB-Hz<div class=bar><div class=fill style="width:'+Math.min(100,s.snr*2)+'%"></div></div></div>').join('')}catch(e){live.textContent='● DISCONNECTED';live.className='bad'}}setInterval(u,500);u()</script></body></html>)";}
void api(){auto&d=nmea.data();JsonDocument j;j["fix"]=d.fix;j["latitude"]=d.latitude;j["longitude"]=d.longitude;j["altitude"]=d.altitude;j["speed_kmh"]=d.speedKmh;j["satellites"]=d.satellites;j["hdop"]=d.hdop;j["last_nmea"]=d.lastSentence;j["packets"]=packets;auto a=j["satellite_view"].to<JsonArray>();for(int i=0;i<nmea.satelliteCount();i++){auto&s=nmea.satellites()[i];auto o=a.add<JsonObject>();o["constellation"]=s.constellation;o["prn"]=s.prn;o["snr"]=s.snr;}String b;serializeJson(j,b);web.send(200,"application/json",b);}
void setup(){Serial.begin(115200);GNSS.begin(9600,SERIAL_8N1,16,17);GPSOut.begin(9600,SERIAL_8N1,-1,18);WiFi.mode(WIFI_AP);WiFi.softAP("NavIC-GPS-Bridge","navicgps");tcp.begin();web.on("/",[]{web.send(200,"text/html",page());});web.on("/api/live",api);web.begin();}
void loop(){web.handleClient();WiFiClient incoming=tcp.available();if(incoming)for(auto&c:clients)if(!c||!c.connected()){c=incoming;break;}while(GNSS.available()){String l=GNSS.readStringUntil('\n');l.trim();if(!l.length())continue;if(!nmea.process(l)){invalid++;continue;}packets++;String o=nmea.gpsCompatible(l);GPSOut.println(o);for(auto&c:clients)if(c&&c.connected())c.println(o);}}