#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <ArduinoJson.h>
#include <Update.h>
#include "NMEAEngine.h"
#include "Settings.h"
#include "GnssLogger.h"
#include "TrackExport.h"
#include "EventEngine.h"

HardwareSerial GNSS(1),GPSOut(2);WebServer web(80);WiFiServer tcp(10110);WiFiClient clients[4];NMEAEngine nmea;SettingsManager settings;GnssLogger logger;EventEngine events;unsigned long packets=0,invalid=0,lastDataMs=0;String wifiMode="AP";
bool protectedRoute(){auto &c=settings.get();if(!c.webAuthEnabled)return true;if(web.authenticate(c.webUsername.c_str(),c.webPassword.c_str()))return true;web.requestAuthentication();return false;}
void sendJson(const JsonDocument&j){String b;serializeJson(j,b);web.send(200,"application/json",b);}
void live(){auto&d=nmea.data();JsonDocument j;j["fix"]=d.fix;j["latitude"]=d.latitude;j["longitude"]=d.longitude;j["altitude"]=d.altitude;j["speed_kmh"]=d.speedKmh;j["satellites"]=d.satellites;j["hdop"]=d.hdop;j["last_nmea"]=d.lastSentence;j["packets"]=packets;j["data_fresh"]=millis()-lastDataMs<3000;auto a=j["satellite_view"].to<JsonArray>();for(int i=0;i<nmea.satelliteCount();i++){auto&s=nmea.satellites()[i];auto o=a.add<JsonObject>();o["constellation"]=s.constellation;o["prn"]=s.prn;o["snr"]=s.snr;}sendJson(j);}
void configGet(){auto&c=settings.get();JsonDocument j;j["gnss_baud"]=c.gnssBaud;j["gps_out_baud"]=c.gpsOutBaud;j["tcp_port"]=c.tcpPort;j["gps_compatibility"]=c.gpsCompatibility;j["ap_enabled"]=c.apEnabled;j["sta_enabled"]=c.staEnabled;j["sta_ssid"]=c.staSsid;j["web_auth_enabled"]=c.webAuthEnabled;j["web_username"]=c.webUsername;j["password_set"]=c.webPassword.length()>0;sendJson(j);}
void configPost(){JsonDocument j;auto e=deserializeJson(j,web.arg("plain"));if(e){web.send(400,"application/json","{\"ok\":false,\"error\":\"invalid_json\"}");return;}BridgeConfig c=settings.get();if(j["gnss_baud"].is<uint32_t>())c.gnssBaud=j["gnss_baud"];if(j["gps_out_baud"].is<uint32_t>())c.gpsOutBaud=j["gps_out_baud"];if(j["tcp_port"].is<uint16_t>())c.tcpPort=j["tcp_port"];if(j["gps_compatibility"].is<bool>())c.gpsCompatibility=j["gps_compatibility"];if(j["ap_enabled"].is<bool>())c.apEnabled=j["ap_enabled"];if(j["sta_enabled"].is<bool>())c.staEnabled=j["sta_enabled"];if(j["sta_ssid"].is<String>())c.staSsid=j["sta_ssid"].as<String>();if(j["sta_password"].is<String>())c.staPassword=j["sta_password"].as<String>();if(j["web_auth_enabled"].is<bool>())c.webAuthEnabled=j["web_auth_enabled"];if(j["web_username"].is<String>())c.webUsername=j["web_username"].as<String>();if(j["web_password"].is<String>()&&j["web_password"].as<String>().length())c.webPassword=j["web_password"].as<String>();if(c.gnssBaud<1200||c.gnssBaud>921600||c.gpsOutBaud<1200||c.gpsOutBaud>921600||c.tcpPort<1024){web.send(422,"application/json","{\"ok\":false,\"error\":\"invalid_settings\"}");return;}settings.save(c);web.send(200,"application/json","{\"ok\":true,\"restart_required\":true}");}
void restartDevice(){web.send(200,"application/json","{\"ok\":true,\"restarting\":true}");delay(300);ESP.restart();}void resetDevice(){settings.reset();web.send(200,"application/json","{\"ok\":true,\"reset\":true}");delay(300);ESP.restart();}
void diagnostics(){JsonDocument j;j["uptime_s"]=millis()/1000;j["free_heap"]=ESP.getFreeHeap();j["packets"]=packets;j["invalid"]=invalid;j["wifi_mode"]=wifiMode;j["ip"]=wifiMode=="AP"?WiFi.softAPIP().toString():WiFi.localIP().toString();int c=0;for(auto&x:clients)if(x&&x.connected())c++;j["clients"]=c;sendJson(j);}
void alerts(){auto&e=events.last();JsonDocument j;j["message"]=e.message;j["timestamp_ms"]=e.timestamp;j["count"]=events.count();sendJson(j);}void security(){JsonDocument j;j["enabled"]=settings.get().webAuthEnabled;j["username"]=settings.get().webUsername;sendJson(j);}
void trackJson(){JsonDocument j;j["points"]=logger.size();j["capacity"]=GnssLogger::MAX_POINTS;sendJson(j);}void trackCsv(){String out="timestamp_ms,latitude,longitude,altitude_m,speed_kmh\n";for(size_t i=0;i<logger.size();i++){auto&p=logger.at(i);out+=String(p.timestamp)+","+String(p.lat,7)+","+String(p.lon,7)+","+String(p.altitude,2)+","+String(p.speedKmh,2)+"\n";}web.sendHeader("Content-Disposition","attachment; filename=navic-gps-track.csv");web.send(200,"text/csv",out);}void trackGpx(){web.send(200,"application/gpx+xml",trackToGpx(logger));}void trackKml(){web.send(200,"application/vnd.google-earth.kml+xml",trackToKml(logger));}
void otaDone(){web.send(200,"text/plain",Update.hasError()?"OTA failed":"OTA successful. Restarting…");delay(300);if(!Update.hasError())ESP.restart();}void otaUpload(){HTTPUpload&u=web.upload();if(u.status==UPLOAD_FILE_START)Update.begin(UPDATE_SIZE_UNKNOWN);else if(u.status==UPLOAD_FILE_WRITE){if(Update.write(u.buf,u.currentSize)!=u.currentSize)Update.abort();}else if(u.status==UPLOAD_FILE_END)Update.end(true);}
void setup(){Serial.begin(115200);settings.begin();auto&c=settings.get();GNSS.begin(c.gnssBaud,SERIAL_8N1,16,17);GPSOut.begin(c.gpsOutBaud,SERIAL_8N1,-1,18);WiFi.mode(WIFI_AP);WiFi.softAP("NavIC-GPS-Bridge","navicgps");tcp.begin();web.on("/",[]{if(protectedRoute())web.send(200,"text/plain","NavIC GPS Bridge: use /api/live or configuration API");});web.on("/api/live",[]{if(protectedRoute())live();});web.on("/api/config",HTTP_GET,[]{if(protectedRoute())configGet();});web.on("/api/config",HTTP_POST,[]{if(protectedRoute())configPost();});web.on("/api/restart",HTTP_POST,[]{if(protectedRoute())restartDevice();});web.on("/api/reset",HTTP_POST,[]{if(protectedRoute())resetDevice();});web.on("/api/diagnostics",[]{if(protectedRoute())diagnostics();});web.on("/api/alerts",[]{if(protectedRoute())alerts();});web.on("/api/security",[]{if(protectedRoute())security();});web.on("/api/track",[]{if(protectedRoute())trackJson();});web.on("/api/track.csv",[]{if(protectedRoute())trackCsv();});web.on("/api/track.gpx",[]{if(protectedRoute())trackGpx();});web.on("/api/track.kml",[]{if(protectedRoute())trackKml();});web.on("/api/track/clear",HTTP_POST,[]{if(!protectedRoute())return;logger.clear();web.send(200,"application/json","{\"ok\":true}");});web.on("/api/ota",HTTP_POST,otaDone,otaUpload);web.begin();}
void loop(){web.handleClient();WiFiClient incoming=tcp.available();if(incoming)for(auto&c:clients)if(!c||!c.connected()){c=incoming;break;}while(GNSS.available()){String l=GNSS.readStringUntil('\n');l.trim();if(!l.length())continue;if(!nmea.process(l)){invalid++;continue;}packets++;lastDataMs=millis();auto&d=nmea.data();logger.add(d.latitude,d.longitude,d.altitude,d.speedKmh,millis());events.update(d,true,millis());String o=nmea.gpsCompatibility? nmea.gpsCompatible(l):l;GPSOut.println(o);for(auto&c:clients)if(c&&c.connected())c.println(o);}events.update(nmea.data(),millis()-lastDataMs<3000,millis());}