#include "NMEAEngine.h"
static String f(const String&s,int n){int a=0,c=0;for(int i=0;i<=s.length();++i)if(i==s.length()||s[i]==','){if(c++==n)return s.substring(a,i);a=i+1;}return "";}
bool NMEAEngine::checksumValid(const String&l)const{if(!l.startsWith("$"))return false;int x=l.indexOf('*');if(x<0||x+2>=l.length())return false;auto hex=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='A'&&c<='F')return c-'A'+10;if(c>='a'&&c<='f')return c-'a'+10;return -1;};int hi=hex(l[x+1]),lo=hex(l[x+2]);if(hi<0||lo<0)return false;uint8_t s=0;for(int i=1;i<x;i++)s^=l[i];return uint8_t((hi<<4)|lo)==s;}
double NMEAEngine::parseCoordinate(const String&v,const String&h)const{if(v.length()<4)return 0;int d=(h=="N"||h=="S")?2:3;double r=v.substring(0,d).toDouble()+v.substring(d).toDouble()/60;if(h=="S"||h=="W")r=-r;return r;}
String NMEAEngine::sourceForTalker(const String&t)const{if(t=="GP")return "GPS";if(t=="GI")return "NavIC";if(t=="GN")return "GNSS";if(t=="GA")return "Galileo";if(t=="GL")return "GLONASS";if(t=="GB"||t=="BD")return "BeiDou";return "Unknown";}
void NMEAEngine::parseGsv(const String&l,const String&t){if(f(l,2).toInt()==1)satCount=0;for(int b=4;b<=16&&satCount<32;b+=4){String p=f(l,b);if(!p.length())break;auto&s=sats[satCount++];s.constellation=t=="GP"?"GPS":t=="GI"?"NavIC":t=="GA"?"Galileo":t=="GL"?"GLONASS":t=="GB"?"BeiDou":t;s.prn=p.toInt();s.elevation=f(l,b+1).toInt();s.azimuth=f(l,b+2).toInt();s.snr=f(l,b+3).toInt();}}
bool NMEAEngine::process(const String&l){if(!checksumValid(l)||l.length()<7)return false;state.lastSentence=l;String t=l.substring(1,3),type=l.substring(3,6);state.source=sourceForTalker(t);if(type=="RMC"){state.utcTime=f(l,1);state.valid=f(l,2)=="A";state.latitude=parseCoordinate(f(l,3),f(l,4));state.longitude=parseCoordinate(f(l,5),f(l,6));state.speedKmh=f(l,7).toDouble()*1.852;state.course=f(l,8).toDouble();state.utcDate=f(l,9);state.fix=state.valid;if(state.fix)lastFixMillis=millis();}else if(type=="GGA"){state.fixQuality=f(l,6).toInt();state.satellites=f(l,7).toInt();state.hdop=f(l,8).toDouble();state.altitude=f(l,9).toDouble();state.fix=state.fixQuality>0;state.valid=state.fix;if(state.fix)lastFixMillis=millis();}else if(type=="GSV")parseGsv(l,t);return true;}
bool NMEAEngine::fixFresh(uint32_t nowMs,uint32_t maxAgeMs)const{return state.fix&&(uint32_t)(nowMs-lastFixMillis)<=maxAgeMs;}
String NMEAEngine::gpsCompatible(const String&l)const{int x=l.indexOf('*');String p=x>=0?l.substring(1,x):l.substring(1);if(p.startsWith("GN"))p="GP"+p.substring(2);uint8_t s=0;for(int i=0;i<p.length();i++)s^=p[i];char b[4];snprintf(b,4,"*%02X",s);return "$"+p+String(b);}
