#include "NMEAEngine.h"
static String f(const String&s,int n){int a=0,c=0;for(int i=0;i<=s.length();++i)if(i==s.length()||s[i]==','){if(c++==n)return s.substring(a,i);a=i+1;}return "";}
static bool validCoordinate(const String&v,const String&h,bool latitude){if(v.length()<4)return false;if(latitude){if(h!="N"&&h!="S")return false;}else if(h!="E"&&h!="W")return false;int d=latitude?2:3;if(v.length()<=d)return false;for(int i=0;i<v.length();++i){char c=v[i];if(i==d)continue;if(c=='.'&&i>d)continue;if(c<'0'||c>'9')return false;}int deg=v.substring(0,d).toInt();if((latitude&&deg>90)||(!latitude&&deg>180))return false;double minutes=v.substring(d).toDouble();return minutes>=0.0&&minutes<60.0;}
bool NMEAEngine::checksumValid(const String&l)const{if(!l.startsWith("$"))return false;int x=l.indexOf('*');if(x<0||x+2>=l.length())return false;auto hex=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='A'&&c<='F')return c-'A'+10;if(c>='a'&&c<='f')return c-'a'+10;return -1;};int hi=hex(l[x+1]),lo=hex(l[x+2]);if(hi<0||lo<0)return false;uint8_t s=0;for(int i=1;i<x;i++)s^=l[i];return uint8_t((hi<<4)|lo)==s;}
double NMEAEngine::parseCoordinate(const String&v,const String&h)const{if(v.length()<4)return 0;int d=(h=="N"||h=="S")?2:3;double r=v.substring(0,d).toDouble()+v.substring(d).toDouble()/60;if(h=="S"||h=="W")r=-r;return r;}
String NMEAEngine::sourceForTalker(const String&t)const{if(t=="GP")return "GPS";if(t=="GI")return "NavIC";if(t=="GN")return "GNSS";if(t=="GA")return "Galileo";if(t=="GL")return "GLONASS";if(t=="GB"||t=="BD")return "BeiDou";return "Unknown";}
void NMEAEngine::parseGsv(const String&l,const String&t){if(f(l,2).toInt()==1)satCount=0;for(int b=4;b<=16&&satCount<32;b+=4){String p=f(l,b);if(!p.length())break;auto&s=sats[satCount++];s.constellation=t=="GP"?"GPS":t=="GI"?"NavIC":t=="GA"?"Galileo":t=="GL"?"GLONASS":t=="GB"?"BeiDou":t;s.prn=p.toInt();s.elevation=f(l,b+1).toInt();s.azimuth=f(l,b+2).toInt();s.snr=f(l,b+3).toInt();}}
bool NMEAEngine::process(const String&l){if(!checksumValid(l)||l.length()<7)return false;state.lastSentence=l;String t=l.substring(1,3),type=l.substring(3,6);if(type=="RMC"||type=="GGA")state.source=sourceForTalker(t);if(type=="RMC"){state.utcTime=f(l,1);state.valid=f(l,2)=="A";String lat=f(l,3),latH=f(l,4),lon=f(l,5),lonH=f(l,6);if(state.valid&&!validCoordinate(lat,latH,true))return false;if(state.valid&&!validCoordinate(lon,lonH,false))return false;state.latitude=parseCoordinate(lat,latH);state.longitude=parseCoordinate(lon,lonH);state.speedKmh=f(l,7).toDouble()*1.852;state.course=f(l,8).toDouble();state.utcDate=f(l,9);state.fix=state.valid;if(state.fix)lastFixMillis=millis();}else if(type=="GGA"){state.fixQuality=f(l,6).toInt();state.satellites=f(l,7).toInt();state.hdop=f(l,8).toDouble();state.altitude=f(l,9).toDouble();String lat=f(l,2),latH=f(l,3),lon=f(l,4),lonH=f(l,5);state.fix=state.fixQuality>0;if(state.fix&&(!validCoordinate(lat,latH,true)||!validCoordinate(lon,lonH,false))){state.fix=false;state.valid=false;return false;}state.valid=state.fix;if(state.fix){state.latitude=parseCoordinate(lat,latH);state.longitude=parseCoordinate(lon,lonH);lastFixMillis=millis();}}else if(type=="GSV")parseGsv(l,t);return true;}
bool NMEAEngine::fixFresh(uint32_t nowMs,uint32_t maxAgeMs)const{return state.fix&&(uint32_t)(nowMs-lastFixMillis)<=maxAgeMs;}
String NMEAEngine::fixState(uint32_t nowMs,uint32_t maxAgeMs)const{if(!state.fix)return "NO_FIX";return fixFresh(nowMs,maxAgeMs)?"FIX_VALID":"FIX_STALE";}
GnssData NMEAEngine::currentData(uint32_t nowMs,uint32_t maxAgeMs)const{GnssData snapshot=state;if(state.fix&&!fixFresh(nowMs,maxAgeMs)){snapshot.fix=false;snapshot.valid=false;}return snapshot;}
String NMEAEngine::gpsCompatible(const String&l)const{int x=l.indexOf('*');String p=x>=0?l.substring(1,x):l.substring(1);if(p.startsWith("GN")||p.startsWith("GI"))p="GP"+p.substring(2);uint8_t s=0;for(int i=0;i<p.length();i++)s^=p[i];char b[4];snprintf(b,4,"*%02X",s);return "$"+p+String(b);}
